nginx:
  image: nginx:1.9
  ports:
    - "80:80"
  links: 
    - web
  volumes:
    - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    - ./nginx/metacvserver-nginx.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - web
