db:
  image: postgres:9.4 
  volumes_from: 
    - dbdata
  environment:
    - POSTGRES_PASSWORD
    - POSTGRES_USER=monsieurarbre
    - POSTGRES_DB=metacvserver

dbdata:
  image: busybox
  volumes: 
    - /var/lib/postgresql/data

web:
  build: metacvserver/
  links: 
    - db
  volumes_from:
    - webmedia 
  environment:
    - POSTGRES_PASSWORD

webmedia:
  image: busybox
  volumes:
    - /var/django/metacvserver_media/
